import 'package:dart_exception/dart_exception.dart' as dart_exception;

void main(List<String> arguments) {
  print('Hello world: ${dart_exception.calculate()}!');
}
